### ISSUE TITLE
Controller called when navigating 

### ISSUE THREAD

**Issue by markstratman** [sgbj/generator-aspnetcore-angular2#1]
The HomeController is called as you navigate the app.  To fix:
1. Add `"Microsoft.AspNetCore.SpaServices": "1.0.0-beta-000004"` to the dependencies in `project.json` 
2. Execute `dotnet restore` 
3. Replace `app.UseMvc(routes...` in `Startup.cs` with  

```
app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{*path}",
                    defaults: new { controller = "home", action = "index" }
                );

                routes.MapSpaFallbackRoute("spa-fallback", new { controller = "Home", action = "Index" });
            });
```

**Comment by sgbj** [comment]
Thanks for the fix! I've made the suggested changes.
