### ISSUE TITLE
error install node packages

### ISSUE THREAD

**Issue by TheSniper102** [sgbj/generator-aspnetcore-angular2#10]
after typing install
i got the following error

"tsc : The term 'tsc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
- tsc
- ~~~
  - CategoryInfo          : ObjectNotFound: (tsc:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException"
    ![installerror](https://cloud.githubusercontent.com/assets/5757313/17085276/b7adc210-51d4-11e6-9416-056b370c338e.png)

i checked the directory and opend solution file the solution not loaded

**Comment by sgbj** [comment]
`tsc` is the TypeScript compiler. You need to install the npm [typescript](https://www.npmjs.com/package/typescript) package globally in order to use that command.

Run
`npm install -g typescript`

Then run
`tsc`

I have plans to make this process a little easier in the future. I apologize for the inconvenience.

**Comment by TheSniper102** [comment]
project not opend
![error open solution file](https://cloud.githubusercontent.com/assets/5757313/17099906/85500fde-526b-11e6-95b4-224b40d46843.png)
![splutionplace](https://cloud.githubusercontent.com/assets/5757313/17099907/85526432-526b-11e6-98fd-11857fbe3cf6.png)

**Comment by sgbj** [comment]
Do you have both Visual Studio Update 3 and .NET Core 1.0 for Visual Studio installed from https://www.microsoft.com/net/core?

**Comment by TheSniper102** [comment]
no update 2

**Comment by sgbj** [comment]
Please ensure that you have VS Update 3 and .NET Core 1.0 installed. If you still have problems after that, then reopen this issue.
