### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by sgbj** [sgbj/generator-aspnetcore-angular2#21]
Original issuefrom @epiii in #20:

> ![why](https://cloud.githubusercontent.com/assets/4952287/19405376/0e87030a-92a1-11e6-8454-666f25c0544e.jpg)
> excuse me Sir. I use your lib, but when I ran the code, I got this error. 
> could you help me ?
> this is my project : https://github.com/epiii/rplExercise/tree/master/aspAngu
> thanks in advance

**Comment by sgbj** [comment]
@epiii I cloned your repository and I was able to get it working by running `npm install` and `dotnet run`. Unfortunately, there's not a whole lot of information to go on from your screenshot. 

What steps did you take to run this application?
Is there more information in that error message that you can provide? 
What version of Firefox are you using? 
Does the networking tab of Firebug have any errors or bad requests?

**Comment by epiii** [comment]
[solved]
sorry @sgbj  I forget to install typescript etc
this is screenshot from forum that i followed 
![solved boy](https://cloud.githubusercontent.com/assets/4952287/19411702/ad095642-9330-11e6-94d4-edafd4588d03.jpg)

thank you @sgbj

**Comment by sgbj** [comment]
Glad you got it working. I'll close this issue. Feel free to reopen it if you run into any other issues.
