### ISSUE TITLE
Changes to HTML reverts back to original template

### ISSUE THREAD

**Issue by shermmyy** [sgbj/generator-aspnetcore-angular2#28]
I have a completely new project using the Advanced template.

Steps to reproduce:
1. Load the webpage via localhost:3000
2. Change the home page HTML in some way ... for example, rename the first tab "home" to "homesss"
3. Refresh the web page
4. The changed tab "homesss" appears for a split second and then reverts back to its original name "home"

This seems to be an issue with not refreshing the dist folder with the compiled changes.
If I delete the dist folder and build again, the same thing happens, but this time - the "original" state the tab name reverts back to is "homesss"

Something to look at: at the end of dist/main.bundle.js is the "original" html that it always reverts back to. This file looks like it's loaded last, so it might be overwritting whatever changes were loaded first

**Comment by sgbj** [comment]
Are you running the app from the command line? Did you set the `ASPNETCORE_ENVIRONMENT` environment variable to `Development`? The webpack dev middleware is only applied when the environment is set to development.

**Comment by shermmyy** [comment]
Yup the environment variable was it. Forgot I wasn't on a windows command prompt and had to update it in my bash_profile ....
