### ISSUE TITLE
yo aspnetcore-angular2 causes Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by jmogera** [sgbj/generator-aspnetcore-angular2#31]
Once i get this error. I run "npm install webpack", and then it causes another error: cannot find module 'webpack-merge'.

**Comment by peske** [comment]
The same here.

**Comment by sgbj** [comment]
What happens when you combine the `dependencies` and `devDependencies` sections in your `package.json` file and run `npm install` and `npm run build`?

**Comment by jmogera** [comment]
I think the issue is related to ng2-bootstrap. https://github.com/npm/npm/issues/15248. Removed ng2-bootstrap..  did npm install... then installed ng2-bootstrap.
