### ISSUE TITLE
Can't debug with VS Code

### ISSUE THREAD

**Issue by markstratman** [sgbj/generator-aspnetcore-angular2#4]
Debugging does not work with Visual Studio Code.  Added `"debugType": "portable"` to `"buildOptions"` in `project.json` to resolve it.  https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs

To debug using VS Code open the `..\src\WebApp` directory with VS Code.  VS Code will prompt you to add assets to build and debug, click `Yes`.   A `.vscode` directory will be created containing `launch.json` and `tasks.json`

**Comment by sgbj** [comment]
I've made the suggested changes. Thanks!
