### ISSUE TITLE
No Swagger?

### ISSUE THREAD

**Issue by bradygaster-zz** [sgbj/generator-aspnetcore-angular2#6]
One of the things I had enjoyed about this template was its inclusion of support for Swagger via Swashbuckle. It seems like a recent commit mitigated this around the Core RC2/AngularJS RC1 upgrade time frame. Is there a plan to re-add it? Less an issue and more a point of curiosity on its removal from the template. 

I'd be interested in adding it if in via a fork unless there's a reason for its removal. Thanks!

**Comment by sgbj** [comment]
This was an oversight on my part, sorry about that. I didn't bother to check if there was a package available for Core RC2, and I didn't notice the version change from rc1-final to beta-9, so I removed the dependency. I'd love to add it back in though.

Let me know if you want to make the change, otherwise I can take care of it.

**Comment by bradygaster-zz** [comment]
@sgbj i'd love to do that. :) i'll update my fork and add it. i have a talk coming up on campus and was planning on using this template as a kick-starter to that talk. so i may as well contribute to the project i'll be using, huh? i have a few large irons in the fire right now so it'll be a day or two but yes, i'd love to make this change. 

I'm new to these templates so this may be a super-n00b question - as I'm working on the template is there an easy way to test it since you probably shouldn't accept random PRs just for the purpose of my testing. if you want to take the discussion to email we can do that, but any guidance (even if it's the CLI commands i'd execute) would be helpful. 

Thanks!

**Comment by sgbj** [comment]
That's awesome, I appreciate it a lot.

So... I should've been creating unit tests as I work on this, but I haven't so I apologize for that. For right now what you can do to test it is clone the repository and `cd` into the root directory of the repository and then type `npm link`. You can then go to some other directory and try out `yo aspnetcore-angular2`, and it'll run your local copy of the generator. You can make changes in your repository and re-run `yo aspnetcore-angular2` to see those changes.

Sorry about the manual process, I should really work on some unit tests.

**Comment by bradygaster-zz** [comment]
No worries @sgbj this commentary is super-helpful.

**Comment by sgbj** [comment]
I went ahead and added Swagger back in since I was already making changes for .NET Core 1.0. I hope that's alright with you. If you have any more suggestions please feel free to share them.
