### ISSUE TITLE
Asp.Net Core 1.0

### ISSUE THREAD

**Issue by MistyKuu** [sgbj/generator-aspnetcore-angular2#7]
When can we expect an update for Release version of ASP.NET?

**Comment by sgbj** [comment]
I'll try to get it done this weekend. Thanks!

**Comment by MistyKuu** [comment]
Thanks for quick answer. Are you going to consider moving from tsd to typings as tsd is deprecated?

**Comment by sgbj** [comment]
Thanks for the information, I'll be sure look into it. Could you create a separate issue so I can track it separately?

**Comment by sgbj** [comment]
This should be resolved.
